// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: warmer_service.proto

package warmer

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// WarmerdClient is the client API for Warmerd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WarmerdClient interface {
}

type warmerdClient struct {
	cc grpc.ClientConnInterface
}

func NewWarmerdClient(cc grpc.ClientConnInterface) WarmerdClient {
	return &warmerdClient{cc}
}

// WarmerdServer is the server API for Warmerd service.
// All implementations must embed UnimplementedWarmerdServer
// for forward compatibility
type WarmerdServer interface {
	mustEmbedUnimplementedWarmerdServer()
}

// UnimplementedWarmerdServer must be embedded to have forward compatible implementations.
type UnimplementedWarmerdServer struct {
}

func (UnimplementedWarmerdServer) mustEmbedUnimplementedWarmerdServer() {}

// UnsafeWarmerdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WarmerdServer will
// result in compilation errors.
type UnsafeWarmerdServer interface {
	mustEmbedUnimplementedWarmerdServer()
}

func RegisterWarmerdServer(s grpc.ServiceRegistrar, srv WarmerdServer) {
	s.RegisterService(&Warmerd_ServiceDesc, srv)
}

// Warmerd_ServiceDesc is the grpc.ServiceDesc for Warmerd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Warmerd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "warmerd.v1.Warmerd",
	HandlerType: (*WarmerdServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "warmer_service.proto",
}
